#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

TESTS_FAILED=false
FORMATTING_FAILED=false
LINT_FAILED=false
ASTRO_CHECK_FAILED=false

echo "\n Checking code with husky 🐺\n"

echo " ⏳ Format check running..."
echo ""

if npm run format &> /dev/null; then
  echo "  ✅ Prettier passed."
else
  FORMATTING_FAILED=true
  echo "  ❌ Prettier found errors. Please fix the formatting errors before pushing."
fi

echo ""
echo " ⏳ Lint check running..."
echo ""

if npm run lint &> /dev/null; then
  echo "  ✅ ESLint passed."
else
  LINT_FAILED=true
  echo "  ❌ ESLint found errors. Please fix the linting errors before pushing."
fi

echo ""
echo " ⏳ Tests check running..."
echo ""

if npm test &> /dev/null; then
  echo "  ✅ Tests check passed!"
else
  echo "  ❌ Tests check failed (Oops❗️)"
  TESTS_FAILED=true
fi

echo ""
echo " ⏳ Astro type check running..."
echo ""

if npm run check &> /dev/null; then
  echo "  ✅ Astro check passed."
else
  ASTRO_CHECK_FAILED=true
  echo "  ❌ Astro check failed. Please fix the issues before pushing."
fi

echo ""
echo ""

if [ "$FORMATTING_FAILED" = "true" ] || [ "$LINT_FAILED" = "true" ] || [ "$TESTS_FAILED" = "true" ] || [ "$ASTRO_CHECK_FAILED" = "true" ]; then
  echo "\033[0;31m🚨  Due to an error in one of the checks, git push attempt was aborted\033[0m"
  
  if [ "$FORMATTING_FAILED" = "true" ]; then
    echo ""
    echo "💡 For more information about format errors, run 'npm run format'"
    echo "💡 To auto-fix, run 'npm run format:fix'"
  fi
  
  if [ "$LINT_FAILED" = "true" ]; then
    echo ""
    echo "💡 For more information about lint errors, run 'npm run lint'"
    echo "💡 To auto-fix, run 'npm run lint:fix'"
  fi
  
  if [ "$TESTS_FAILED" = "true" ]; then
    echo ""
    echo "💡 For more information about failing tests, run 'npm test'"
  fi
  
  if [ "$ASTRO_CHECK_FAILED" = "true" ]; then
    echo ""
    echo "💡 For more information about Astro type errors, run 'npm run check'"
  fi
  
  echo ""
  echo "💡 Or run 'npm run validate' to see all errors at once"
  echo ""
  exit 1
else
  echo "\033[0;32mGood job mate!\033[0m"
  echo ""
  echo "Pushing Code..."
  echo ""
  exit 0
fi
